chore: added retry for flaky ttranslate test
GoogleCloudPlatform/golang-samples pull request #1860
Opened 2020-12-09 21:10 UTC by munkhuushmgl

Fixes #1572

2020-12-09 22:06 UTC, tbpg requested changes
Thanks!

2020-12-09 22:06 UTC, tbpg commented on translate/v3/batch_translate_text_test.go
> +			t.Fatalf("batchTranslateText: %v", err)
```suggestion
			r.Fatalf("batchTranslateText: %v", err)
			return
```

2020-12-09 22:06 UTC, tbpg commented on translate/v3/batch_translate_text_test.go
> +			t.Errorf("batchTranslateText got:\n----\n%s----\nWant to contain:\n----\n%s\n----", got, want)
```suggestion
			r.Errorf("batchTranslateText got:\n----\n%s----\nWant to contain:\n----\n%s\n----", got, want)
```

2020-12-11 19:33 UTC, munkhuushmgl commented
@tbpg Looks like all the checks are passed, PTAL

2020-12-16 01:58 UTC, tbpg approved these changes
Thanks!

2020-12-16 02:08 UTC, merged