chore(bigquery): add verbose logging to flaky test.
GoogleCloudPlatform/golang-samples pull request #1869
Opened 2020-12-14 21:18 UTC by shollyman

The storage quickstart is flaky, but there's not enough diagnostic
information to implicate why.  This PR adds the stderr output to the log
when the test errors.

Related issue:
https://github.com/GoogleCloudPlatform/golang-samples/issues/1866

2020-12-15 16:17 UTC, tbpg requested changes

2020-12-15 16:17 UTC, tbpg commented on bigquery/bigquery_storage_quickstart/main_test.go
> +		log.Printf("stderr: %s", string(stdErr))
Please use `t.Log`.

2020-12-15 22:00 UTC, shollyman commented on bigquery/bigquery_storage_quickstart/main_test.go
> +		log.Printf("stderr: %s", string(stdErr))
Done.

2020-12-16 00:45 UTC, tbpg approved these changes

2020-12-16 00:46 UTC, merged