feat(eventarc): use eventarc library for pubsub sample
GoogleCloudPlatform/golang-samples pull request #2049
Opened 2021-04-12 20:46 UTC by grant

Uses the eventarc Golang library for our Eventarc Pub/Sub type.

Automatic base64 decoding for the pub/sub data is a FR, not included here.

fixes https://github.com/GoogleCloudPlatform/golang-samples/issues/1645

2021-04-13 17:18 UTC, grant commented
If we get https://github.com/googleapis/google-cloudevents-go/pull/58 in, then we could include the pubsub data base64 decoding here as well.

2021-04-14 03:27 UTC, grant commented
@grayside PTAL at this PR with the updated CE library.

2021-04-19 16:50 UTC, grayside requested changes
Unstable event type libraries shouldn't be used in samples.

2021-04-19 21:20 UTC, grant commented
Per sync with @grayside, we'll create a GitHub issue to clarify the stability of each library and re-visit this PR with the stability evidence backing this PR up.

2021-05-20 15:18 UTC, grant commented
Waiting for Go library to update per @grayside request before re-requesting review for this PR.

2021-07-27 19:23 UTC, closed without merging