feat(spanner): add samples for low-cost instances
GoogleCloudPlatform/golang-samples pull request #2119
Opened 2021-06-25 02:16 UTC by hengfengli

2021-06-25 02:39 UTC, hengfengli commented
@tbpg I tried to run `goimports -w . && find . -name go.mod -execdir go mod tidy \;` locally but couldn't see any updates. Do you know why the `Lint` check fails?

2021-06-25 03:26 UTC, hengfengli commented
After I upgraded the cloud spanner to 1.21.0, I run the command and I can see some updates (complained by the Lint check). However, the Lint check still fails. When I try to run the command again, I couldn't see any updates.

2021-06-25 06:37 UTC, olavloite approved these changes

2021-06-25 06:37 UTC, olavloite commented on spanner/spanner_snippets/spanner/spanner_create_instance_with_processing_units.go
> +		return err
nit: add context information to error

2021-06-30 03:01 UTC, hengfengli commented
@codyoss Can you please help us to merge this PR? Thanks!

2021-06-30 13:19 UTC, codyoss requested changes
Just a couple of small things

2021-06-30 13:19 UTC, codyoss commented on spanner/spanner_snippets/spanner/spanner_create_instance_with_processing_units.go
> +func createInstanceWithProcessingUnits(ctx context.Context, w io.Writer, projectID, instanceID string) error {
nit: Please declare [context as needed](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md#declare-a-contextcontext-as-needed)

2021-06-30 13:19 UTC, codyoss commented on spanner/spanner_snippets/spanner/spanner_create_instance_with_processing_units.go
> +	instanceAdmin, err := instance.NewInstanceAdminClient(ctx)
nit: Please provide [example args](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md#function-arguments-for-snippets).

2021-06-30 14:18 UTC, codyoss approved these changes
LGTM, thank you!

2021-06-30 15:58 UTC, merged