samples: add default leader options samples
GoogleCloudPlatform/golang-samples pull request #2178
Opened 2021-08-05 18:51 UTC by asthamohta

2021-08-09 00:58 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +}
I think we should have a space between functions.

2021-08-09 01:05 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_list_databases.go
> +	printDatabases := func(iter *database.DatabaseIterator) error {
do we need to define this function? why can't we put the loop iteration outside?

2021-08-09 02:27 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +		return fmt.Errorf("createDatabaseWithCustomerManagedEncryptionKey: invalid database id %q", db)
`createDatabaseWithCustomerManagedEncryptionKey`  does not match this sample's name.

2021-08-09 02:37 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +		var OPTION_NAME, OPTION_VALUE string
these two variables should not be capitalized.

2021-08-09 02:46 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +	stmt := spanner.Statement{SQL: `SELECT SingerId, AlbumId, MarketingBudget FROM Albums`}
The query is incorrect. This should be a query to the info schema.

2021-08-09 02:49 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_get_database_ddl.go
> +	fmt.Fprintf(w, "Database DDL is as follows: \n [%s]", op.GetStatements())
is `%v` better?

2021-08-09 02:59 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +	assertContains(t, out, fmt.Sprintf("Available leader options for instance config"))
`fmt.Sprintf(` is not needed. Same for below similar cases.

2021-08-09 03:00 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +	instName, dbName, cleanup := initTest(t, randomID())
`dbName` is never used.

2021-08-09 03:05 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +	instName, dbName, cleanup := initTest(t, randomID())
My bad. My editor gives me a wrong info.

2021-08-09 03:06 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +	//Try to Query Information Schema Database Options
Add a space before `Try`.

2021-08-09 03:08 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +	t.SkipNow()
Why t.SkipNow()? We should remove this.

2021-08-09 03:19 UTC, hengfengli requested changes
Thanks for making these samples so quick. There are some places need to be fixed. I don't think the current test instance would work since it is a regional instance. 

We need to change the `createTestInstance` method to make `InstanceConfig` as a parameter: 

https://github.com/GoogleCloudPlatform/golang-samples/blob/43677838ad7c8772d3b86b50b9146f824cea644f/spanner/spanner_snippets/spanner/integration_test.go#L674

If not given, use `regional-us-central1` as default.

2021-08-10 04:43 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +	instName, cleanup = createTestInstance(t, projectID, false)
It's better to pass the instance config name as a param instead of a boolean value.

2021-08-10 04:44 UTC, hengfengli commented on spanner/spanner_snippets/spanner/integration_test.go
> +func initTestWithConfig(t *testing.T, id string) (instName, dbName string, cleanup func()) {
We should allow the caller to set the instance config: 

```go
func initTestWithConfig(t *testing.T, id, instanceConfigName string) (instName, dbName string, cleanup func()) {

instName, cleanup = createTestInstance(t, projectID, instanceConfigName)
```

2021-08-10 04:49 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +		fmt.Fprintf(w, "The result of the query to get %s for %s is %s", option_name, databaseId, option_value)
nits: for Go's conventions, it should be `databaseID`. I guess you got this from the existing codebase. But better to fix it.

2021-08-10 08:07 UTC, hengfengli approved these changes
Thanks a lot for working on this. LGTM.

2021-08-10 08:08 UTC, hengfengli commented
@codyoss Can we get an approval from you? Thanks.

2021-08-11 03:45 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +	matches := regexp.MustCompile("^(.+)/databases/(.+)$").FindStringSubmatch(db)
@codyoss Do you suggest we change to: 

```go
func queryInformationSchemaDatabaseOptions(w io.Writer, projectID, instanceID, databaseID string) error {
```

But the thing is that when we create the client we still need to construct the full path: 

```go
        // db = `projects/<project>/instances/<instance-id>/database/<database-id>`
	client, err := spanner.NewClient(ctx, db)
```

Another thing is that in most of the existing samples, we pass the full path as a parameter. We probably would like to follow the same convention.

2021-08-11 03:53 UTC, codyoss commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +	matches := regexp.MustCompile("^(.+)/databases/(.+)$").FindStringSubmatch(db)
Unless that values are used individually I would say no. Just one db string /w an example should be fine.

2021-08-11 03:59 UTC, hengfengli commented on spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
> +	matches := regexp.MustCompile("^(.+)/databases/(.+)$").FindStringSubmatch(db)
Does this mean that this comment is resolved? Sorry I got a bit confused.

2021-08-11 04:01 UTC, hengfengli commented
@codyoss A strange thing is that the four CI tests are getting stuck since last night. Do you know what it is the reason?

2021-08-11 17:32 UTC, codyoss approved these changes

2021-08-12 03:49 UTC, merged