feat(compute): add create manage windows instances samples
GoogleCloudPlatform/golang-samples pull request #2540
Opened 2022-04-25 23:24 UTC by FrodoTheTrue

2022-04-26 16:15 UTC, enocom requested changes

2022-04-26 16:15 UTC, enocom commented on compute/instances/create-manage-windows-instances/create_windows_server_external_ip.go
> +		InstanceResource: &computepb.Instance{
The line lengths on this request type are going to require lots of horizontal scrolling.

What if we pulled the `&computepb.Instance{}` into it's own variable to help with this?

``` golang
inst := &computepb.Instance{ /* ... */ }
req := &computepb.InsertInstanceRequest{
    // ...
    InstanceResource: inst,
}
```

2022-04-27 14:40 UTC, FrodoTheTrue commented on compute/instances/create-manage-windows-instances/create_windows_server_internal_ip.go
> +// createWndowsServerInstanceInternalIP creates a new Windows Server instance that has only an internal IP address.
Does it mean that we should modify all files to not to exceed 100 characters?

2022-04-27 15:47 UTC, enocom commented on compute/instances/create-manage-windows-instances/create_windows_server_internal_ip.go
> +// createWndowsServerInstanceInternalIP creates a new Windows Server instance that has only an internal IP address.
Generally, yes. https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#line-length.

2022-04-29 15:55 UTC, enocom approved these changes

2022-04-29 21:04 UTC, merged