feat(compute): custom vm type samples 3
GoogleCloudPlatform/golang-samples pull request #2549
Opened 2022-05-02 23:05 UTC by FrodoTheTrue

2022-05-03 15:49 UTC, enocom approved these changes

2022-05-03 15:50 UTC, enocom commented
@FrodoTheTrue There are some test errors that look pretty simple to fix. The sample itself looks good.

2022-05-03 15:51 UTC, codyoss requested changes
Just a couple small things, thanks for the PR.

2022-05-03 15:51 UTC, codyoss commented on compute/instances/custom-machine-type/custom_machine_type_test.go
> +		t.Errorf("createInstanceWithCustomMachineType got err: %v", err)
for these test consider if the test is still valid if a precondition fails. For example if the instance is never created in this step you are unable to modify or get the instance so this should fail the test with a t.Fatalf.

2022-05-03 15:51 UTC, codyoss commented on compute/instances/custom-machine-type/update_memory.go
> +// to the Compute Engine API and wait for it to complete.
nit: waits

2022-05-05 15:28 UTC, codyoss approved these changes

2022-05-05 16:50 UTC, merged