feat(compute): add samples for suspend/resume
GoogleCloudPlatform/golang-samples pull request #2574
Opened 2022-05-25 09:59 UTC by FrodoTheTrue

2022-05-26 18:52 UTC, muncus requested changes

2022-05-26 18:52 UTC, muncus commented on compute/instances/suspend-resume/resume.go
> +		// f"Only suspended instances can be resumed. "
looks like some leftover comments which can be removed.

2022-05-26 18:52 UTC, muncus commented on compute/instances/suspend-resume/resume.go
> +func resumeInstance(
This indentation style seems inconsistent with other samples. While I dont see any explicit guidance on function signatures, most others are on a single line.

2022-05-26 18:52 UTC, muncus commented on compute/instances/suspend-resume/suspend_resume_test.go
> +		t.Errorf("unable to create instance: %v", err)
This should be Fatalf(), since we cannot continue the test without a VM.

2022-06-06 08:46 UTC, FrodoTheTrue commented
@muncus could you please take a look once more? I've fixed the comments

2022-06-08 17:24 UTC, muncus approved these changes
Thanks for the PR, Fedor!

2022-06-09 08:40 UTC, merged