feat(spanner): add samples for database roles
GoogleCloudPlatform/golang-samples pull request #2579
Opened 2022-05-28 01:59 UTC by varuncnaik

Adds samples with database roles on requests.

2022-05-28 04:20 UTC, varuncnaik commented
I'll work on a sample for ListDatabaseRoles soon.

2022-05-31 17:16 UTC, enocom approved these changes

2022-06-30 18:03 UTC, enocom commented
@varuncnaik Looks like there are some compilation errors caused by missing types. You'll need to upgrade the underlying client if these are new methods and types you're using.

2022-08-10 21:26 UTC, enocom commented
@varuncnaik Still seeing some compilation errors. Let me know if you'd like some help with this. Otherwise, I'll assume you ping me when you're ready for another look.

2022-10-06 16:22 UTC, enocom commented
Looks like we're still missing some types:

```
# github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets
spanner_snippets/snippet.go:825:3: unknown field 'DatabaseRole' in struct literal of type "cloud.google.com/go/spanner".ClientConfig
# github.com/GoogleCloudPlatform/golang-samples/spanner/spanner_snippets/spanner
spanner_snippets/spanner/spanner_read_data_with_database_role.go:32:3: unknown field 'DatabaseRole' in struct literal of type "cloud.google.com/go/spanner".ClientConfig
```

@varuncnaik Want some help finishing this? We've had this open for quite awhile now.

2022-10-18 22:25 UTC, varuncnaik commented
Hi @enocom, we're aware of the missing types. In my local setup for this PR, I'm editing my go.mod file to replace cloud.google.com/go/spanner with my local copy of https://github.com/googleapis/google-cloud-go/pull/5701.

We plan to merge both of these PRs around the time that Cloud Spanner fine-grained access control becomes generally available. Until then, I am periodically merging the latest `main` into both PRs and making sure that tests pass locally. CC @rahul2393, in case the two of you want to exchange information over DM.

2022-10-19 19:07 UTC, enocom commented
Sounds good. Just ping me when you're ready and we can merge this.

2022-11-17 06:19 UTC, rahul2393 commented on spanner/spanner_snippets/spanner/spanner_add_and_drop_database_roles.go
> +// [START spanner_add_and_drop_database_roles]
```suggestion
// [START spanner_add_and_drop_database_roles]
```
// [START spanner_add_and_drop_database_role]

2022-11-17 06:19 UTC, rahul2393 commented on spanner/spanner_snippets/spanner/spanner_add_and_drop_database_roles.go
> +// [END spanner_add_and_drop_database_roles]
```suggestion
// [END spanner_add_and_drop_database_role]
```

2022-11-17 06:21 UTC, rahul2393 requested changes
LGTM with minor change.

2023-01-10 03:12 UTC, rahul2393 approved these changes

2023-01-10 05:38 UTC, merged