docs(cloudnl): update classification sample to use v2 model
GoogleCloudPlatform/golang-samples pull request #2717
Opened 2022-09-23 08:59 UTC by wizeng23

Updates CloudNL Classification sample to use the v2 model.

2022-09-23 15:37 UTC, quartzmo commented
Build error:

```
Error: analyze/analyze.go:135:3: unknown field 'ClassificationModelOptions' in struct literal of type "google.golang.org/genproto/googleapis/cloud/language/v1".ClassifyTextRequest
Error: analyze/analyze.go:135:43: undefined: language.ClassificationModelOptions
Error: analyze/analyze.go:136:16: undefined: language_pb
Error: analyze/analyze.go:137:15: undefined: language_pb
Error: analyze/analyze.go:138:42: undefined: language.ClassificationModelOptions_V2Model_V2
```

2022-09-24 00:19 UTC, wizeng23 commented
Those fields were added in this commit on 9/20: https://github.com/googleapis/googleapis/commit/05b99f982df9837c294ea3475a571a9252c68326. When will the next regeneration of .pb.go files be? If possible, it would be nice to get this PR merged in by Tuedsay.

2022-09-27 17:14 UTC, quartzmo approved these changes

2022-09-27 20:35 UTC, quartzmo requested changes

2022-09-27 20:35 UTC, quartzmo commented on language/analyze/analyze.go
> +		},
I pulled the branch to see if I could get it working locally, and I think I did. Here's what you should do:

1. In `language` dir, run: `go get google.golang.org/genproto`.
   You should see output like: `go: upgraded google.golang.org/genproto v0.0.0-20220201184016-50beb8ab5c44 => v0.0.0-20220927151529-dcaddaf36704`
1. Run `go mod tidy`.
1. Update your changes to:
   ```go
		ClassificationModelOptions: &languagepb.ClassificationModelOptions{
			ModelType: &languagepb.ClassificationModelOptions_V2Model_{
				V2Model: &languagepb.ClassificationModelOptions_V2Model{
					ContentCategoriesVersion: languagepb.ClassificationModelOptions_V2Model_V2,
				},
			},
   ```

2022-09-27 21:09 UTC, quartzmo approved these changes

2022-09-28 02:58 UTC, merged