Initial Batch sample
GoogleCloudPlatform/golang-samples pull request #2736
Opened 2022-10-10 18:12 UTC by Shnatsel

I'm opening this PR to get feedback on style early. I need to write 5 more samples for Batch, so I want to figure it out before I have to edit 5 of these for any changes.

This is meant to be a close translation of https://github.com/googleapis/python-batch/pull/22 and https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2775

I've experimented with initializing entire structs at once instead of using `new(SomeType)` and then assigning fields, but it caused rather unpleasant rightward drift:
https://github.com/GoogleCloudPlatform/golang-samples/blob/205b9e49a31d0594da19eda9b6077519d25445aa/batch/create_with_script_no_mounting.go

TODO:
 - [ ] Write the rest of the samples once the style is settled
 - [ ] Add tests

2022-10-10 22:14 UTC, enocom commented
@Shnatsel The rightward drift actually looks better to me. To handle the long lines, we can pull out child variables for things like `TaskGroup` and `AllocationPolicy`. Using `new` and building a structure piece by piece is actually less common in Go.

Would you mind updating with the suggestion above and we can polish this together?

2022-10-11 14:05 UTC, Shnatsel commented
I've split the megastructure construction into a bunch of smaller structures, still constructed by value instead of via field assignment, as you have suggested.

I think this is more readable than either of the previous layouts.

Is there anything else I should change, or am I good to go to I start working on the other 5 samples?

2022-10-12 18:10 UTC, enocom requested changes
Snippets are looking good. We just need some tests now.

2022-10-12 18:10 UTC, enocom commented on batch/create_with_container_no_mounting.go
> +		Commands:   []string{"-c", "echo Hello world! This is task ${BATCH_TASK_INDEX}. This job has a total of ${BATCH_TASK_COUNT} tasks."},
To avoid horizontal scroll let's shorten the command to something like:

```
"echo Task = ${BATCH_TASK_INDEX} Total = ${BATCH_TASK_COUNT}"
```

2022-10-12 18:10 UTC, enocom commented on batch/create_with_container_no_mounting.go
> +		CpuMilli:  2000, // in milliseconds per cpu-second. This means the task requires 2 whole CPUs.
Let's move the comment above CpiMilli.

2022-10-12 18:10 UTC, enocom commented on batch/create_with_container_no_mounting.go
> +	maxRunDuration := &durationpb.Duration{
nit: these two short declarations could just be inlined.

2022-10-12 18:10 UTC, enocom commented on batch/create_with_container_no_mounting.go
> +		Commands:   []string{"-c", "echo Hello world! This is task ${BATCH_TASK_INDEX}. This job has a total of ${BATCH_TASK_COUNT} tasks."},
Ditto below.

2022-10-12 18:10 UTC, enocom commented on batch/create_with_container_no_mounting.go
> +	maxRunDuration := &durationpb.Duration{
Ditto below.

2022-10-14 16:35 UTC, enocom commented
@Shnatsel when you're ready for another pass, just re-request a review above.

2022-10-19 18:07 UTC, Shnatsel commented
@enocom I'm done adding samples, and I've covered all of them by test. I'd appreciate another look so I could merge this. Thanks!

2022-10-19 19:44 UTC, enocom approved these changes

2022-10-19 19:45 UTC, merged