feat(dlp): added a sample for de-identify replace
GoogleCloudPlatform/golang-samples pull request #2997
Opened 2023-04-26 08:21 UTC by AarshD-crest

## Description
- Added a sample for [de-identify replace](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-replace)
Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [X] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [X] Please **merge** this PR for me once it is approved

2023-04-27 16:55 UTC, telpirion requested changes

2023-04-27 16:55 UTC, telpirion commented on dlp/snippets/deid/deid_replace.go
> +		return fmt.Errorf("DeidentifyContent: %v", err)
nit: use `%w` formatting or don't wrap error.

2023-04-27 16:55 UTC, telpirion commented on dlp/snippets/deid/deid_test.go
> +	buf := new(bytes.Buffer)
issue: don't use `new`. Instead write `var buf bytes.Buffer`.

2023-04-28 08:47 UTC, AarshD-crest commented on dlp/snippets/deid/deid_test.go
> +	buf := new(bytes.Buffer)
Resolved.

2023-04-28 08:47 UTC, AarshD-crest commented on dlp/snippets/deid/deid_replace.go
> +		return fmt.Errorf("DeidentifyContent: %v", err)
Resolved.

2023-05-01 06:04 UTC, annadata approved these changes
LGTM

2023-05-04 18:06 UTC, merged