feat(run/receive-auth): add samples for receive-auth func as same python one
GoogleCloudPlatform/golang-samples pull request #3004
Opened 2023-04-27 09:23 UTC by ryuji-cre8ive

## Description
* check jwt with email from the request.
* almost same func as python one
  * https://github.com/GoogleCloudPlatform/python-docs-samples/blob/HEAD/run/service-auth/receive.py 

Fixes #2986
Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [x] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

2023-04-27 16:47 UTC, telpirion requested changes

2023-04-27 16:47 UTC, telpirion commented on run/service-auth/receive.go
> +	authType, creds := authValues[0], authValues[1]
nit: put a newline before this to improve readability.

2023-04-27 16:47 UTC, telpirion commented on run/service-auth/receive.go
> +		token, err := jwt.Parse(creds, func(token *jwt.Token) (interface{}, error) {
issue: run `gofmt` to ensure that this line is properly formatted. This looks a bit jumbled up and hard to read.

2023-04-27 16:47 UTC, telpirion commented on run/service-auth/receive.go
> +		claims, ok := token.Claims.(jwt.MapClaims)
nit: insert newline before this line to improve readability.

2023-04-27 16:47 UTC, telpirion commented on run/service-auth/receive.go
> +		email, ok := claims["email"].(string)
nit: insert newline before this line to improve readability.

2023-04-27 16:47 UTC, telpirion commented on run/service-auth/receive.go
> +	} else {
issue: rewrite this without the `else` clause.  Add a new check before line 61 like this:

```go
if authType != "Bearer" {
        fmt.Fprintf(w, "Unhandled header format (%v).\n", authType)
}
```

2023-05-01 09:50 UTC, ryuji-cre8ive commented
How can I correct the error of `snippet-bot check — snippet-bot check`
should tags be 
```
[START cloudrun_<any-name-you-want>_dockerfile]
[START run_<any-name-you-want>_dockerfile] 
```


, shouldn't it?
that's why I named 
```
[START cloudrun_serviceauth_dockerfile]
[START run_serviceauth_dockerfile]
```

Thank you

2023-05-04 16:52 UTC, telpirion requested changes

2023-05-04 16:52 UTC, telpirion commented on run/service-auth/receive.go
> +	authType, creds := authValues[0], authValues[1]
Please don't resolve unaddressed comments without at least an "ack" and a reason why you haven't accepted the feedback.

2023-05-04 16:52 UTC, telpirion commented on run/service-auth/receive.go
> +		token, err := jwt.Parse(creds, func(token *jwt.Token) (interface{}, error) {
See previous comment about providing a reason why comments are unaddressed.

2023-05-04 16:52 UTC, telpirion commented on run/service-auth/receive.go
> +		claims, ok := token.Claims.(jwt.MapClaims)
See previous comment about providing a reason why comments are unaddressed.

2023-05-04 16:52 UTC, telpirion commented on run/service-auth/receive.go
> +		email, ok := claims["email"].(string)
See previous comment about providing a reason why comments are unaddressed.

2023-05-04 16:54 UTC, telpirion commented
Please be sure that you are [following code review best practices](https://google.github.io/eng-practices/review/developer/handling-comments.html#code) with your pull requests.

2023-05-09 18:18 UTC, telpirion commented
> How can I solve the error of `snippet-bot check — snippet-bot check` should tags be
> 
> ```
> [START cloudrun_<any-name-you-want>_dockerfile]
> [START run_<any-name-you-want>_dockerfile] 
> ```
> 
> , shouldn't it? that's why I named
> 
> ```
> [START cloudrun_serviceauth_dockerfile]
> [START run_serviceauth_dockerfile]
> ```
> 
> Thank you

It looks like the correct region tag prefix is `cloudrun`.

2023-05-16 19:45 UTC, telpirion commented
Author hasn't addressed comments and this sample hasn't been planned for. Closing this PR.

2023-05-16 19:45 UTC, closed without merging