feat(securitycenter): add scc samples for mute config
GoogleCloudPlatform/golang-samples pull request #3094
Opened 2023-05-17 08:46 UTC by Sita04

## Description

Add new SCC samples for mute config.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [ ] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [ ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-05-17 08:50 UTC, Sita04 commented
The tests need 2 env variables: `SCC_PROJECT_ORG_ID` and `SCC_PROJECT_ID`

2023-05-17 16:47 UTC, telpirion requested changes
There are a few global issues here that need to be resolved:

- Always be sure that the client closes before a method exits.
- Break up test cases so that one sample gets one test case.
- Do setup in `TestMain()` rather than in the test case.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/go.mod
> +go 1.16
issue: revert. please do not decrease the Go language level.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/create_mute_rule.go
> +
issue: insert `defer client.Close()`.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/delete_mute_rule.go
> +
issue: insert `defer client.Close()`.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/get_mute_rule.go
> +
issue: insert `defer client.Close()`.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/list_mute_rules.go
> +
issue: insert `defer client.Close()`.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/mute_config_test.go
> +	t.Parallel()
issue: please remove. Unless your tests must run in parallel, this will cause issues.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/mute_config_test.go
> +	if err := setupResources(); err != nil {
issue: do resource setup in `TestMain(m *testing.M)`, not inside of the test case.

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/mute_config_test.go
> +	if err := listMuteRules(buf, parent); err != nil {
issue: Only one sample test per test case. Move this into a new test case (e.g. `TestListMuteRules(t *testing.T)`).

2023-05-17 16:47 UTC, telpirion commented on securitycenter/muteconfig/mute_config_test.go
> +	if err := getMuteRule(buf, parent, muteConfigId1); err != nil {
issue: one sample test per test case.

2023-05-17 20:23 UTC, Sita04 commented
@telpirion Thanks for the review! I've updated the samples acc to your comments.

2023-05-24 16:30 UTC, telpirion approved these changes

2023-05-24 16:30 UTC, telpirion approved these changes

2023-05-24 17:03 UTC, merged