feat(dlp): added a sample for dlp redact image all infotypes
GoogleCloudPlatform/golang-samples pull request #3152
Opened 2023-05-30 07:04 UTC by AarshD-crest

## Description

- Added a sample for [dlp redact image all infotypes](https://cloud.google.com/dlp/docs/samples/dlp-redact-image-all-infotypes) with a unit test case.

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [X] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-05-31 05:55 UTC, annadata approved these changes

2023-06-05 18:14 UTC, telpirion requested changes

2023-06-05 18:14 UTC, telpirion commented on dlp/snippets/redact/testdata/image.jpg
Please remove trademarked material:

+ Honda
+ Accord
+ LX

2023-06-06 05:14 UTC, AarshD-crest commented on dlp/snippets/redact/testdata/image.jpg
Updated it.

2023-06-08 16:51 UTC, telpirion approved these changes

2023-06-14 16:28 UTC, merged