feat(dlp): added a sample for dlp create stored infotype
GoogleCloudPlatform/golang-samples pull request #3191
Opened 2023-06-29 06:18 UTC by AarshD-crest

## Description

- Added a sample of dlp_create_stored_infotype with a unit test case. 
- Just for reference mentioning that Based on a discussion with @annadata we have decided to skip the test in the test pipeline for such samples.

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [X] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [X] Please **merge** this PR for me once it is approved

2023-06-30 11:10 UTC, annadata approved these changes

2023-06-30 17:20 UTC, telpirion requested changes

2023-06-30 17:20 UTC, telpirion commented on dlp/snippets/metadata/metadata_test.go
> +	"github.com/gofrs/uuid"
Please use `github.com/google/uuid ` instead.

2023-07-03 10:26 UTC, AarshD-crest commented on dlp/snippets/metadata/metadata_test.go
> +	"github.com/gofrs/uuid"
Updated.

2023-07-18 18:09 UTC, telpirion approved these changes

2023-07-18 20:57 UTC, merged