Adds aiplatform top level folder with initial PaLM API samples
GoogleCloudPlatform/golang-samples pull request #3231
Opened 2023-07-27 00:29 UTC by ghchinoy

## Description

Adds aiplatform top level folder with initial PaLM API samples

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

2023-08-03 20:08 UTC, telpirion requested changes

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-embeddings/embeddings_test.go
> +	projectID := "PROJECT_ID"
issue: use `testutil.SystemTest(t)` here to get the `TestContext`. You can access the project ID from the `TestContext`.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +// [START aiplatform_text_predictions]
issue: move region tags before `import` statement.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	log.Printf("apiendpoint: %s", apiEndpoint)
issue: remove `log.Printf()` here.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	c, err := aiplatform.NewPredictionClient(ctx, option.WithEndpoint(apiEndpoint))
issue: replace `c` with `client`.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +		log.Printf("unable to create prediction client: %v", err)
issue: replace `log.Printf()` with `fmt.Fprintf()`.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	// PredictRequest requires an Endpoint, Instances, and Parameters
issue: see previous about capitalization.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +		log.Printf("unable to convert prompt to Value: %v", err)
issue: use `fmt.Fprintf()` and return error here.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +		log.Printf("unable to convert parameters to Value: %v", err)
issue: same as previous (use `fmt.Fprintf()` and return error).

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	// PredictRequest
issue: provide more explanatory comment or cut.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	log.Printf("PredictRequest.Endpoint:   %v", req.GetEndpoint())
issue: cut these three lines.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +		log.Printf("error in prediction: %v", err)
issue: use `fmt.Fprintf()` here.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	jsonData, err := json.MarshalIndent(resp, "", " ")
issue/question: can you access the fields of the `PredictResponse` here instead?

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text.go
> +	log.Printf("%s\n", jsonData)
issue: cut this line.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text_test.go
> +	//testutil.SystemTest(t)
issue:  uncomment.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text_test.go
> +	//"github.com/GoogleCloudPlatform/golang-samples/internal/testutil"
issue: uncomment.

2023-08-03 20:08 UTC, telpirion commented on aiplatform/text-predict/text_test.go
> +	projectID := "PROJECT_ID"
issue: access the ProjectID field from the object returned from `testutil.SystemTest(t)`.

2023-08-03 22:43 UTC, ghchinoy commented on aiplatform/text-embeddings/embeddings.go
> +	log.Printf("PredictRequest.Endpoint:   %v", req.GetEndpoint())
They were, yes -  will cut.

2023-08-03 22:46 UTC, ghchinoy commented on aiplatform/text-embeddings/embeddings.go
> +	req := &aiplatformpb.PredictRequest{
In the test, the Parameters are assigned and govern the text model attributes (temperature, max output tokens, top P, top K)

2023-08-03 22:47 UTC, ghchinoy commented on aiplatform/text-embeddings/embeddings.go
> +	// PredictResponse
Will add more information

2023-08-03 22:47 UTC, ghchinoy commented on aiplatform/text-embeddings/embeddings.go
> +	jsonData, err := json.MarshalIndent(resp, "", " ")
Yes, another debug artifact to be removed. thank you!

2023-08-04 19:34 UTC, telpirion approved these changes

2023-08-04 19:34 UTC, telpirion commented on aiplatform/text-embeddings/embeddings_test.go
> +	testutil.SystemTest(t)
nit: `SystemTest` returns an object that you can keep a reference for later (e.g. line 29).

2023-08-04 19:34 UTC, telpirion commented on aiplatform/text-predict/text_test.go
> +	testutil.SystemTest(t)
Same as previous: you can capture a reference to the return value of `SystemTest` and then dot into it below.

2023-08-04 19:53 UTC, merged