feat(vertexai): Add stream text sample
GoogleCloudPlatform/golang-samples pull request #4147
Opened 2024-05-23 03:47 UTC by ymotongpoo

## Description

Go porting of the following Python sample: 
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/inference/stream_text_basic.py

Region tag is `generativeaionvertexai_stream_text_basic`

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

2024-05-24 18:21 UTC, grayside requested changes
Thanks for the sample, I've asked for a small change to unblock approval. The feedback is identical to what I left on #4148

2024-05-27 03:46 UTC, ymotongpoo commented on vertexai/stream-text-basic/streamtextbasic.go
> +		}
ACK. I added the case for empty response. same as #4148.

2024-05-27 03:48 UTC, ymotongpoo commented on vertexai/stream-text-basic/streamtextbasic.go
> +}
ACK. Inlined the custom print function content into the main function.

2024-05-29 17:57 UTC, grayside approved these changes
LGTM, thank you!

2024-05-29 18:34 UTC, merged