feat(compute): compute_spot_create/check samples
GoogleCloudPlatform/golang-samples pull request #4187
Opened 2024-06-14 10:11 UTC by irudykss

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [ ] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [ ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2024-06-24 19:18 UTC, muncus requested changes

2024-06-24 19:18 UTC, muncus commented on compute/instances/spot/create_spot.go
> +	image, err := getImageFromFamily("debian-cloud", "debian-11")
these helper functions obscure the flow of code. please refactor this to inline your helper functions, so the code is more readable.

consider this related sample: https://github.com/GoogleCloudPlatform/golang-samples/blob/main/compute/instances/create-start-instance/create_instance_from_public_image.go#L29

2024-06-24 19:18 UTC, muncus commented on compute/instances/spot/spot_test.go
> +func TestSpotCreate(t *testing.T) {
please combine these test cases. there's no need to create 2 spot vms for these checks.

2024-06-28 06:42 UTC, m-strzelczyk approved these changes

2024-06-30 17:04 UTC, merged