chore(samples): Add samples for Cloud Spanner Default Backup Schedules
GoogleCloudPlatform/golang-samples pull request #4527
Opened 2024-11-07 15:40 UTC by Sally-Ye

## Description

This PR adds code samples for cloud spanner default backup schedules using the following apis:
1. CreateInstance
2. UpdateInstance

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [ ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [X] Please **merge** this PR for me once it is approved

2024-11-07 17:43 UTC, telpirion requested changes

2024-11-07 17:43 UTC, telpirion commented on spanner/spanner_snippets/spanner/spanner_create_instance_without_default_backup_schedule.go
> +	i, err := op.Wait(ctx)
issue: use a more descriptive name for this variable. What type is `i`? if I wanted to look up reference documentation about it, what would I lookup?

2024-11-07 17:43 UTC, telpirion commented on spanner/spanner_snippets/spanner/spanner_update_instance_default_backup_schedule_type.go
> +	req := &instancepb.UpdateInstanceRequest{
issue: update operations are a commonly confused task for developers. Provide a comment above the request object that describes:

1. What field in the resource is being updated.
2. Why the FieldMask must be included.

2024-11-07 17:43 UTC, telpirion commented on spanner/spanner_snippets/spanner/spanner_update_instance_default_backup_schedule_type.go
> +func updateInstanceDefaultBackupScheduleType(w io.Writer, projectID, instanceID string) error {
issue: provide a short Godoc-style comment that explains what this function does.

2024-11-07 17:43 UTC, telpirion commented on spanner/spanner_snippets/spanner/spanner_create_instance_without_default_backup_schedule.go
> +func createInstanceWithoutDefaultBackupSchedule(w io.Writer, projectID, instanceID string) error {
issue: provide a short Godoc-style comment that explains what this function does.

2024-11-07 17:43 UTC, telpirion commented on spanner/spanner_snippets/spanner/spanner_create_instance_without_default_backup_schedule.go
> +	op, err := instanceAdmin.CreateInstance(ctx, &instancepb.CreateInstanceRequest{
issue(1): move the request object outside of the method call.

issue(2): provide a comment about the request object that describes the features of the resource you're creating.

2024-11-11 19:06 UTC, telpirion approved these changes

2024-11-15 16:50 UTC, harshachinta approved these changes

2024-11-15 18:40 UTC, merged