feat(vertex/aiplatform): add code samples for embeddings
GoogleCloudPlatform/golang-samples pull request #4594
Opened 2024-11-20 13:57 UTC by Valeriy-Burlaka

## Description

Adds code samples for Multimodal Embeddings API (both [Guides](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings) & [API Reference](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/multimodal-embeddings-api) doc trees).

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..`
- [x] **Code formatted**:   `gofmt`
- [x] **Vetting** pass:   `go vet`

2024-11-21 16:28 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image.go
> +	// https://storage.googleapis.com/google-cloud-aiplatform/schema/predict/instance/vision_embedding_model_1.0.0.yaml
The YAML schema definition for the deployed model is the **only** documentation I was able to find. The `PredictRequest.Instances` field [is a generic](https://pkg.go.dev/cloud.google.com/go/aiplatform/apiv1/aiplatformpb#PredictRequest) protobuf `Value`.
Please let me know if there is a better documentation source to link here.

2024-11-21 16:35 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image_and_text.go
> +// [START generativeaionvertexai_multimodal_embedding_image_and_text]
This is a **new** region tag. There is a mistake in the Python [sample](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/embeddings/multimodal_image_example.py#L27), as it re-uses "text+image" example both for "[image](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/multimodal-embeddings-api#image-use-case)" and "[image+text](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings#text-image-embedding)" documentation sections. The text in the documentation clearly separates these 2 cases.

2024-11-21 16:37 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image.go
> +	// https://storage.googleapis.com/google-cloud-aiplatform/schema/predict/prediction/vision_embedding_model_1.0.0.yaml
Same as above: it looks like the YAML schema definition for the deployed model is the only documentation available.

2024-11-21 16:43 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image.go
> +func generateForImage(w io.Writer, project, location string) ([]float32, error) {
[Doc section](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/multimodal-embeddings-api#image-use-case)

2024-11-21 16:44 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image_and_text.go
> +func generateForTextAndImage(w io.Writer, project, location string) ([][]float32, error) {
[Doc section](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings#text-image-embedding)

2024-11-21 16:45 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image_text_and_video.go
> +func generateForImageTextAndVideo(w io.Writer, project, location string) ([][]float32, error) {
Doc sections:
* [Guides](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings#img-txt-vid-embedding)
* [API Reference](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/multimodal-embeddings-api#advanced-use)

2024-11-21 16:46 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_with_lower_dimension.go
> +func generateWithLowerDimension(w io.Writer, project, location string) ([][]float32, error) {
[Doc section](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-multimodal-embeddings#low-dimension)

2024-11-21 18:08 UTC, telpirion commented
Hey @Valeriy-Burlaka -- in the future, would you please break PRs > 500 LoC into multiple PRs? PRs over 500 LoC take quite a bit longer for me to review.

2024-11-21 18:30 UTC, telpirion requested changes
Some global issues on this PR that need to be addressed:

- Anytime you call `fmt.Errorf`, use the `%w` formatting directive rather than `%v`.
- Don't return a type from the samples, just an error. Print the length of the embeddings in the sample text and then check for that using `strings.Contains` in the test.
- Point to the official documentation page on cloud.google.com, even if it lacks some data. I think the response and request body documentation there is sufficient for developer needs.

2024-11-21 18:30 UTC, telpirion commented on vertexai/embeddings/generate_for_image.go
> +		return nil, fmt.Errorf("failed to construct API client: %v", err)
issue: use `%w` here so that we don't lose error data.

2024-11-21 18:30 UTC, telpirion commented on vertexai/embeddings/generate_for_image.go
> +		return nil, fmt.Errorf("failed to construct request payload: %v", err)
Same as previous, use `%w`.

2024-11-21 18:30 UTC, telpirion commented on vertexai/embeddings/generate_for_image.go
> +		Instances: []*structpb.Value{instance}, // The model supports only 1 instance per request
nit: move comment above line to avoid line wrapping.

2024-11-21 18:30 UTC, telpirion commented on vertexai/embeddings/generate_for_image_and_text.go
> +		return nil, fmt.Errorf("failed to construct API client: %v", err)
Same as previous, use `%w`.

2024-11-21 18:37 UTC, Valeriy-Burlaka commented
@telpirion , sorry for a big PR! - I thought that it would be more convenient to review all samples for a given API at once, rather than I'd provide them 1 by 1 and fragment the context.

Regarding linking to the [cloud documentation](I would point to the docs page that you found: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/multimodal-embeddings-api#syntax.): it has one major issue - it's a static (markdown) in the documentation, and it seems that it already fall out of date a bit. For example, the `parameters.dimension` does not have any effect on the generated response, and should be passed as part of `PredictionRequest`.

2024-11-21 18:41 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image_and_text.go
> +	return [][]float32{textEmbedding, imageEmbedding}, nil
Sorry, I thought it's [permitted](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/vertexai/context-caching/contextcaching_create.go#L29) for better test'ability. In my initial iteration, I used `strings.Contains(...)` testing on the buffer, but it looked a bit clunky.

2024-11-22 15:31 UTC, Valeriy-Burlaka commented on vertexai/embeddings/generate_for_image_and_text.go
> +// [START generativeaionvertexai_multimodal_embedding_image_and_text]
I adjusted the region tags to follow what we have in Python to unblock this issue. The region tag `generativeaionvertexai_multimodal_embedding_image` is now pointing to both "Image" and "Text+Image" doc sections and also contains "Text+Image" sample. I find this weird and inaccurate but I understand now may be not the best time to focus on this.

2024-11-22 16:03 UTC, Valeriy-Burlaka commented
@telpirion , @msampathkumar , all issues with the PR should be addressed now. Can you please take a final look? Thanks!

2024-11-29 12:31 UTC, msampathkumar commented
Hi @telpirion  when possible, please re-review this PR. Thanks.

2024-12-02 19:42 UTC, telpirion approved these changes

2024-12-02 20:11 UTC, merged