chore(secretmanager): add optional argument ttl to createSecret
GoogleCloudPlatform/golang-samples pull request #4894
Opened 2024-12-20 19:29 UTC by OremGLG

## Description
chore(secretmanager): add optional argument ttl to createSecret and updated tests with/without ttl

Fixes #(b/384052840)[http://b/384052840]

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [ ] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [ ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2024-12-30 17:25 UTC, OremGLG commented
@iennae I am not sure if you wanted to merge the PR to the main branch...

2025-01-06 18:34 UTC, telpirion requested changes

2025-01-06 18:34 UTC, telpirion commented on secretmanager/create_secret.go
> +func createSecret(w io.Writer, parent, id string, ttl *secretmanagerpb.Secret_Ttl) (*secretmanagerpb.Secret, error) {
issue: do not return a value (other than error) from samples.

See: https://googlecloudplatform.github.io/samples-style-guide/#result

2025-01-06 18:49 UTC, OremGLG commented on secretmanager/create_secret.go
> +func createSecret(w io.Writer, parent, id string, ttl *secretmanagerpb.Secret_Ttl) (*secretmanagerpb.Secret, error) {
Got it, I will correct it

2025-01-08 17:33 UTC, eapl-gemugami commented on secretmanager/create_secret.go
> +func createSecret(w io.Writer, parent, id string, ttl *secretmanagerpb.Secret_Ttl) (*secretmanagerpb.Secret, error) {
@OremGLG I'd say that instead of calling the code in the sample (which must not return a value), you should create another function `testSecretWithTtl` based on `testSecret`:
https://github.com/GoogleCloudPlatform/golang-samples/blob/2245a79b79c32a0c0ec217dc36ba2f6e4b372446/secretmanager/secretmanager_test.go#L88-L110

And then calling that function like in
https://github.com/GoogleCloudPlatform/golang-samples/blob/2245a79b79c32a0c0ec217dc36ba2f6e4b372446/secretmanager/secretmanager_test.go#L217-L222

@telpirion could we do that? My thought process was on adding test coverage for the updated sample. With the optional ttl/expiration and without.

2025-01-08 17:42 UTC, eapl-gemugami commented on secretmanager/create_secret.go
> +func createSecret(w io.Writer, parent, id string, ttl *secretmanagerpb.Secret_Ttl) (*secretmanagerpb.Secret, error) {
@OremGLG as context,
b/384052840 is about adding ttl support to the code sample
b/384941536 is the task I made for the test

2025-01-08 17:46 UTC, OremGLG commented on secretmanager/create_secret.go
> +func createSecret(w io.Writer, parent, id string, ttl *secretmanagerpb.Secret_Ttl) (*secretmanagerpb.Secret, error) {
Thanks, I am working on it

2025-01-14 17:54 UTC, telpirion approved these changes

2025-01-14 18:10 UTC, merged