fix(securitycenter): issues related to flaky tests in SHA & ETD
GoogleCloudPlatform/golang-samples pull request #4898
Opened 2024-12-20 23:23 UTC by vijaykanthm

## Description

Fixes #4866 #4871 Flakiness in tests due to Concurrent Modification error.

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [ ] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [ ] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2025-01-04 00:27 UTC, shayneholmes approved these changes
Thanks for contributing this! This is a speculative PR, since we don't yet know the root cause for the concurrent modification message. We should roll it back if it doesn't fix the underlying issues.

2025-01-06 18:32 UTC, telpirion requested changes
Please use testutil.Retry instead of creating your own retry function.

https://github.com/GoogleCloudPlatform/golang-samples/blob/main/internal/testutil/retry.go

2025-01-10 18:51 UTC, telpirion requested changes
I need a bit more context about what is being attempted with this PR.

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +func cleanupExistingCustomModules(orgID string) error {
issue!: Remove this. We sometimes have tests running in parallel--this could potentially delete a resource used by another test.

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +	mu.Lock()
question: why the mutex here? What shared resource is being protected inside the critical section / this function?

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +	mu.Lock()
Same as previous

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +	mu.Lock()
Same as previous.

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +	mu.Lock()
Same as previous.

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +	mu.Lock()
Same as previous.

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
> +	mu.Lock()
Same as previous.

2025-01-10 18:51 UTC, telpirion commented on securitycenter/management_api/security_health_analytics_custom_module_test.go
> +func cleanupExistingCustomModules(orgID string) error {
See previous about deleting all resources in a organization.

2025-01-14 18:00 UTC, muncus commented
I've looked through the logs for several of these failed builds, and it is only Create and Delete operations that lead to "concurrent modification" errors - To me, this points to the *organization* object being the contended write, not the module. To tackle that, i'd suggest creating a small number of modules in TestMain(), and reusing those modules throughout the tests. The current tests appear to create at least 15 modules.

Another way to approach this is to use [`testutils.Retry`](https://github.com/GoogleCloudPlatform/golang-samples/blob/6e73cbea7f32331254c2706a3b840213f3a45aec/internal/testutil/retry.go#L30) when creating and deleting modules.

2025-01-14 20:16 UTC, vijaykanthm commented
As per the email discussion, closing this PR, will refactor the clean up of resources to avoid the resource contention issue and will raise a new one.

2025-01-14 20:16 UTC, closed without merging